version: "3.9"
services:
    db:
        image: postgres:14.1-alpine
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=enem123
            - POSTGRES_DB=enem
        ports:
            - '5432:5432'
    
    admin:    
        image: adminer    
        ports:      
            - "8080:8080"